import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ar' | 'en';

const translations = {
  ar: {
    explore: 'استكشاف',
    generator: 'المولد',
    pro: 'احترافي',
    creativePrompts: 'أوامر إبداعية',
    signIn: 'تسجيل الدخول',
    profile: 'الملف الشخصي',
    upgrade: 'ترقية إلى Pro',
    logout: 'تسجيل الخروج',
    search: 'بحث',
    curatedMasterpieces: 'روائع منتقاة',
    noPromptsFound: 'لا توجد برومبتات في هذا التصنيف بعد.',
    footerDesc: 'المنصة الأكثر تقدماً للبرومبتات الذكية. نصمم مستقبل المرئيات السينمائية، برومبت تلو الآخر.',
    platform: 'المنصة',
    explorePrompts: 'استكشاف البرومبتات',
    aiGenerator: 'مولد الذكاء الاصطناعي',
    promptAcademy: 'أكاديمية البرومبت',
    communityUpdates: 'تحديثات المجتمع',
    support: 'الدعم',
    helpCenter: 'مركز المساعدة',
    termsOfService: 'شروط الخدمة',
    privacyPolicy: 'سياسة الخصوصية',
    contactUs: 'اتصل بنا',
    rightsReserved: '© 2026 أوامر إبداعية. جميع الحقوق محفوظة.',
    madeWith: 'صُنع بـ',
    forCreativeCommunity: 'للمجتمع الإبداعي.',
    heroBadge: 'استكشف برومبتات أسطورية',
    heroTitle: 'فن البرومبتات المثالية',
    heroSubtitle: 'استكشف مجموعة مختارة من برومبتات الذكاء الاصطناعي الأسطورية. أنشئ مرئيات سينمائية بدقة وأناقة.',
    startExploring: 'ابدأ الاستكشاف',
    tryGenerator: 'جرب المولد',
    scrollIndicator: 'مرر للاستكشاف',
    promptGridSubtitle: 'برومبتات مختارة بعناية مصممة لتحقيق أقصى تأثير وجودة سينمائية.',
    catAll: 'الكل',
    catProduct: 'منتج',
    catLogo: 'شعار',
    catSocial: 'اجتماعي',
    catVideo: 'فيديو',
    catBranding: 'هوية تجارية',
    // Help Center
    helpCenterTitle: 'كيف يمكننا مساعدتك؟',
    helpCenterSubtitle: 'ابحث في الأسئلة الشائعة أو تواصل مع فريق الدعم لدينا.',
    faq: 'الأسئلة الشائعة',
    contactSupport: 'تواصل مع الدعم',
    // Terms of Service
    termsTitle: 'شروط الخدمة',
    termsSubtitle: 'يرجى قراءة هذه الشروط بعناية قبل استخدام منصتنا.',
    // Privacy Policy
    privacyTitle: 'سياسة الخصوصية',
    privacySubtitle: 'نحن نهتم بخصوصيتك ونحمي بياناتك.',
    // Generator
    genTitle: 'صانع البرومبتات الاحترافي',
    genSubtitle: 'حوّل أفكارك البسيطة إلى برومبتات سينمائية احترافية بضغطة زر.',
    genPlaceholder: 'صف فكرتك هنا (مثال: زجاجة عطر فاخرة على بحيرة كريستالية وقت الغروب...)',
    genButton: 'توليد البرومبت الاحترافي',
    genLoading: 'جاري صياغة البرومبت...',
    genInspiration: 'إضافات سريعة (اختر لتعزيز فكرتك):',
    genResultTitle: 'البرومبت الاحترافي',
    genBadge: 'أساسي',
    genCopy: 'نسخ البرومبت',
    genCopied: 'تم النسخ!',
    genVariations: 'تنسيقات بديلة',
    genUseCases: 'أفضل الاستخدامات',
    genProTip: 'نصيحة احترافية',
    genProTipText: 'استخدم هذه البرومبتات مع نموذج "نانو بنانا" (Nano Banana) كنموذج احترافي أول قبل الكل، ثم جربها مع Midjourney v6 أو DALL-E 3 للحصول على أفضل النتائج السينمائية.',
    // Profile
    profLoading: 'جاري تحميل الملف الشخصي...',
    profSignIn: 'يرجى تسجيل الدخول لعرض ملفك الشخصي.',
    profEdit: 'تعديل الملف الشخصي',
    profStats: 'الإحصائيات',
    profGen: 'التوليدات',
    profFav: 'المفضلة',
    profYourFav: 'مفضلاتك',
    profViewAll: 'عرض الكل',
    profNoFav: 'لا توجد مفضلات بعد',
    profNoFavDesc: 'استكشف المعرض واحفظ البرومبتات التي تعجبك.',
    profExploreNow: 'استكشف الآن',
    profNeedCredits: 'تحتاج المزيد من الرصيد؟',
    profUpgradeDesc: 'قم بالترقية إلى Pro واحصل على توليدات غير محدودة وبرومبتات أسطورية.',
    profUpgradeNow: 'قم بالترقية الآن',
    profCredits: 'رصيد',
    profFree: 'مجاني',
    // Edit Profile Modal
    epTitle: 'تعديل الملف الشخصي',
    epName: 'الاسم',
    epEmail: 'البريد الإلكتروني (غير قابل للتعديل)',
    epAvatar: 'الصورة الشخصية',
    epUploadImage: 'رفع صورة',
    epSuggestions: 'اقتراحات عصرية (اختر واحدة أو اتركها)',
    epSave: 'حفظ التغييرات',
    epCancel: 'إلغاء',
    epSuccess: 'تم تحديث الملف الشخصي بنجاح!',
    // Payment Modal
    // (Removed payment translations)
    // Pro Page
    proBadge: 'أطلق العنان لإبداعك',
    proTitle1: 'ارتقِ إلى',
    proTitle2: 'النسخة الاحترافية',
    proSubtitle: 'احصل على وصول غير محدود لأدوات صياغة البرومبتات الأكثر تقدماً في العالم.',
    proWhy: 'لماذا الترقية؟',
    proF1: 'توليد برومبتات غير محدود',
    proF2: 'الوصول إلى البرومبتات الأسطورية',
    proF3: 'أداة تحسين البرومبتات المتقدمة',
    proF4: 'دعم فني بأولوية قصوى',
    proF5: 'وصول مبكر للميزات الجديدة',
    proF6: 'رخصة استخدام تجاري',
    proInstant: 'تفعيل فوري',
    proInstantDesc: 'افتح جميع الميزات فوراً بعد الشراء.',
    proSecure: 'دفع آمن',
    proSecureDesc: 'عملية دفع آمنة ومشفرة بالكامل.',
    proBestValue: 'أفضل قيمة',
    proLifetime: 'وصول مدى الحياة',
    proLifetimeDesc: 'دفع لمرة واحدة، لك إلى الأبد.',
    proGetAccess: 'قم بالترقية الآن',
    proJoin: 'انضم إلى أكثر من 10,000 مبدع يصنعون المستقبل.',
    // Auth Modal
    authJoin: 'انضم إلى Creative Prompts',
    authDesc: 'افتح البرومبتات الأسطورية، واحفظ مفضلاتك، وقم بتوليد روائع سينمائية.',
    authEmail: 'البريد الإلكتروني',
    authPassword: 'كلمة المرور',
    authSignIn: 'تسجيل الدخول',
    authSignUp: 'إنشاء حساب جديد',
    authOr: 'أو',
    authGoogle: 'المتابعة باستخدام Google',
    authTerms: 'بالمتابعة، أنت توافق على شروط الخدمة الخاصة بنا.',
    authNoAccount: 'ليس لديك حساب؟',
    authHasAccount: 'لديك حساب بالفعل؟',
    authCreateOne: 'أنشئ حساباً',
    authLoginHere: 'سجل دخولك هنا',
    authEmailError: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    authEmailInUse: 'هذا البريد الإلكتروني مستخدم بالفعل. يرجى تسجيل الدخول.',
    authWeakPassword: 'كلمة المرور ضعيفة جداً. يجب أن تتكون من 6 أحرف على الأقل.',
    // Gallery Page
    galleryTitle: 'معرض البرومبتات',
    gallerySubtitle: 'استكشف عالم الإبداع',
    galleryDesc: 'مجموعة مختارة من أفضل البرومبتات لإنشاء صور مذهلة باستخدام الذكاء الاصطناعي.',
    gallerySearch: 'ابحث عن برومبت...',
    galleryLoading: 'جاري تحميل البرومبتات...',
    galleryNoResults: 'لم يتم العثور على نتائج.',
    galleryProOnly: 'محتوى خاص بالمشتركين',
    gallerySubscribe: 'اشترك في باقة برو للوصول إلى هذا البرومبت',
    galleryCopy: 'نسخ البرومبت',
    galleryCopied: 'تم النسخ',
    galleryViews: 'مشاهدة',
  },
  en: {
    explore: 'Explore',
    generator: 'Generator',
    pro: 'Pro',
    creativePrompts: 'Creative Prompts',
    signIn: 'Sign In',
    profile: 'Profile',
    upgrade: 'Upgrade to Pro',
    logout: 'Log out',
    search: 'Search',
    curatedMasterpieces: 'Curated Masterpieces',
    noPromptsFound: 'No prompts found in this category yet.',
    footerDesc: 'The world\'s most advanced AI prompt platform. Architecting the future of cinematic visuals, one prompt at a time.',
    platform: 'Platform',
    explorePrompts: 'Explore Prompts',
    aiGenerator: 'AI Generator',
    promptAcademy: 'Prompt Academy',
    communityUpdates: 'Community Updates',
    support: 'Support',
    helpCenter: 'Help Center',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    contactUs: 'Contact Us',
    rightsReserved: '© 2026 Creative Prompts AI. All rights reserved.',
    madeWith: 'Made with',
    forCreativeCommunity: 'for the creative community.',
    heroBadge: 'Explore Legendary Prompts',
    heroTitle: 'The Art of Perfect Prompts',
    heroSubtitle: 'Explore a curated collection of legendary AI prompts. Generate cinematic visuals with precision and elegance.',
    startExploring: 'Start Exploring',
    tryGenerator: 'Try Generator',
    scrollIndicator: 'Scroll to explore',
    promptGridSubtitle: 'Hand-picked prompts designed for maximum impact and cinematic quality.',
    catAll: 'All',
    catProduct: 'Product',
    catLogo: 'Logo',
    catSocial: 'Social',
    catVideo: 'Video',
    catBranding: 'Branding',
    // Help Center
    helpCenterTitle: 'How can we help you?',
    helpCenterSubtitle: 'Search our FAQ or get in touch with our support team.',
    faq: 'Frequently Asked Questions',
    contactSupport: 'Contact Support',
    // Terms of Service
    termsTitle: 'Terms of Service',
    termsSubtitle: 'Please read these terms carefully before using our platform.',
    // Privacy Policy
    privacyTitle: 'Privacy Policy',
    privacySubtitle: 'We care about your privacy and protect your data.',
    // Generator
    genTitle: 'Professional Prompt Architect',
    genSubtitle: 'Transform your simple ideas into professional cinematic prompts with one click.',
    genPlaceholder: 'Describe your idea (e.g., A luxury perfume bottle on a crystal lake at sunset...)',
    genButton: 'Generate Professional Prompt',
    genLoading: 'Architecting magic...',
    genInspiration: 'Quick Add-ons (Click to enhance):',
    genResultTitle: 'The Masterpiece',
    genCopy: 'Copy Prompt',
    genCopied: 'Copied!',
    genVariations: 'Alternative Variations',
    genUseCases: 'Best Use Cases',
    genProTip: 'Pro Tip',
    genProTipText: 'Use these prompts with the "Nano Banana" model as your primary professional model before anything else, then try them with Midjourney v6 or DALL-E 3 for the best cinematic results.',
    // Profile
    profLoading: 'Loading profile...',
    profSignIn: 'Please sign in to view your profile.',
    profEdit: 'Edit Profile',
    profStats: 'Stats',
    profGen: 'Generations',
    profFav: 'Favorites',
    profYourFav: 'Your Favorites',
    profViewAll: 'View All',
    profNoFav: 'No favorites yet',
    profNoFavDesc: 'Explore the gallery and save prompts you love.',
    profExploreNow: 'Explore Now',
    profNeedCredits: 'Need more credits?',
    profUpgradeDesc: 'Upgrade to Pro and get unlimited generations and legendary prompts.',
    profUpgradeNow: 'Upgrade Now',
    profCredits: 'CREDITS',
    profFree: 'FREE',
    // Edit Profile Modal
    epTitle: 'Edit Profile',
    epName: 'Name',
    epEmail: 'Email (Read-only)',
    epAvatar: 'Profile Picture',
    epUploadImage: 'Upload Image',
    epSuggestions: 'Modern Suggestions (Pick one or ignore)',
    epSave: 'Save Changes',
    epCancel: 'Cancel',
    epSuccess: 'Profile updated successfully!',
    // Payment Modal
    // (Removed payment translations)
    // Pro Page
    proBadge: 'UNLEASH YOUR CREATIVITY',
    proTitle1: 'Elevate to',
    proTitle2: 'Creative Prompts Pro',
    proSubtitle: 'Get unlimited access to the world\'s most advanced AI prompt architecture tools.',
    proWhy: 'Why go Pro?',
    proF1: 'Unlimited AI Prompt Generations',
    proF2: 'Access to Legendary Prompts',
    proF3: 'Advanced Prompt Enhancer Tool',
    proF4: 'Priority Support',
    proF5: 'Early Access to New Features',
    proF6: 'Commercial Usage License',
    proInstant: 'Instant Activation',
    proInstantDesc: 'Unlock all features immediately after purchase.',
    proSecure: 'Secure Payment',
    proSecureDesc: 'Safe and encrypted checkout process.',
    proBestValue: 'BEST VALUE',
    proLifetime: 'Lifetime Access',
    proLifetimeDesc: 'One-time payment, forever yours.',
    proGetAccess: 'Upgrade Now',
    proJoin: 'Join 10,000+ creators architecting the future.',
    // Auth Modal
    authJoin: 'Join Creative Prompts',
    authDesc: 'Unlock legendary prompts, save your favorites, and generate cinematic masterpieces.',
    authEmail: 'Email Address',
    authPassword: 'Password',
    authSignIn: 'Sign In',
    authSignUp: 'Create Account',
    authOr: 'OR',
    authGoogle: 'Continue with Google',
    authTerms: 'By continuing, you agree to our Terms of Service.',
    authNoAccount: 'Don\'t have an account?',
    authHasAccount: 'Already have an account?',
    authCreateOne: 'Create one',
    authLoginHere: 'Log in here',
    authEmailError: 'Invalid email or password.',
    authEmailInUse: 'This email is already in use. Please sign in.',
    authWeakPassword: 'Password is too weak. Must be at least 6 characters.',
    // Gallery Page
    galleryTitle: 'Prompt Gallery',
    gallerySubtitle: 'Explore the World of Creativity',
    galleryDesc: 'A curated collection of the best prompts to create stunning AI images.',
    gallerySearch: 'Search prompts...',
    galleryLoading: 'Loading prompts...',
    galleryNoResults: 'No results found.',
    galleryProOnly: 'Pro Only Content',
    gallerySubscribe: 'Subscribe to Pro to access this prompt',
    galleryCopy: 'Copy Prompt',
    galleryCopied: 'Copied',
    galleryViews: 'views',
  }
};

export const LanguageContext = createContext<{
  language: Language;
  toggleLanguage: () => void;
  t: (key: keyof typeof translations.ar) => string;
}>({
  language: 'ar',
  toggleLanguage: () => {},
  t: (key) => translations.ar[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ar');

  const toggleLanguage = () => {
    const newLang = language === 'ar' ? 'en' : 'ar';
    setLanguage(newLang);
    const html = document.documentElement;
    html.setAttribute('lang', newLang);
    html.setAttribute('dir', newLang === 'ar' ? 'rtl' : 'ltr');
  };

  const t = (key: keyof typeof translations.ar) => translations[language][key];

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
